# Generated by Django 5.0.14 on 2026-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
